#!/usr/bin/env bash
ROOT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.."


# exit on error
set -e


cd "$ROOT_DIR"


# upgrade pip install
pip install --upgrade pip setuptools

# install project requirements
pip install --requirement requirements.txt
